[package]
name = "shiny-robots"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]

[dependencies]
futures = "0.1.18"
hyper = "0.11.15"
hyper-tls = "0.1.2"
route-recognizer = "0.1.12"
semver = { version = "0.9.0", features = ["serde"] }
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
slog = "2.1.1"
slog-json = "2.2.0"
tokio-core = "0.1.12"
tokio-service = "0.1.0"
toml = "0.4.5"
