[package]
name = "shiny-robots"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]
edition = "2018"

[workspace]
members = [
    ".",
    "./libs/badge",
]

[dependencies]
badge = { path = "./libs/badge" }

cadence = "0.13"
failure = "0.1"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
indexmap = { version = "1.0.0", features = ["serde-1"] }
lru-cache = "0.1"
maud = "0.22"
once_cell = "1.4"
relative-path = { version = "0.3.7", features = ["serde"] }
route-recognizer = "0.1"
rustsec = "0.6.0"
semver = { version = "0.11", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.9"
shared_failure = "0.1.0"
slog = "2"
slog-json = "2"
tokio-core = "0.1"
tokio-service = "0.1"
toml = "0.5"
try_future = "0.1"


[build-dependencies]
sass-rs = "0.2"
